tutorHut/tutorHut/Controllers/ListController.cs
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;
using tutorHut.Classes;
using tutorHut.Models;

namespace tutorHut.Controllers
{
    public class ListController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: List
        // added string searchString
        public ActionResult Index(string searchString)
        {
            var profiles = db.Profiles.Include(p => p.Address).Include(p => p.ApplicationUser).Include(p => p.Request).Include(p => p.Subject);

            if (!String.IsNullOrEmpty(searchString))
            {
                profiles = profiles.Where(p => p.Subject.SubjectName.Contains(searchString));
            }
            

            return View(profiles.ToList());
        }


        // GET: List/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }


            Profile profile = db.Profiles.Include(d => d.Subject).Include(d => d.ApplicationUser).Where(d => d.ProfileId == id).First();

            if (profile == null)
            {
                return HttpNotFound();
            }
            return View(profile);
        }



        //new code
        //POST
        [HttpPost]
        public ActionResult Details()
        {       
            var userId = User.Identity.GetUserId();
            ApplicationUser user = db.Users.Where(d => d.Id == userId).First();

            Hidden hide = new Hidden();

            if (ModelState.IsValid)
            {
                
                string userEmail = user.Email;
                string linkName = "REPLY";
                string text = "\n\n" + userEmail.ToString() + " \n\nwishes to obtain your contact information. Please click on the REPLY link above to accept or deny this request";
                string email = hide.Email;               
                string subject = "Request Information";
                string link = "<html><body><a href='http://localhost:65515/Reply\'>" + linkName + "</a></body></html>";


                link += text;

                MailGun.SendSimpleMessage(email, subject, link);

                return RedirectToAction("Index");

            }

            return View();
        }


        // GET: List/Create
        public ActionResult Create()
        {
            ViewBag.AddressId = new SelectList(db.Addresses, "AddressId", "StreetAddress");
            ViewBag.UserId = new SelectList(db.Users, "Id", "Email");
            ViewBag.RequestId = new SelectList(db.Requests, "RequestId", "Status");
            ViewBag.SubjectId = new SelectList(db.Subjects, "SubjectID", "SubjectName");
            return View();
        }

        // POST: List/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ProfileId,UserId,AddressId,SubjectId,RequestId,ProfileFirstName,ProfileLastName,ProfilePhoneNumber,HourlyRate,MyDescription")] Profile profile)
        {
            if (ModelState.IsValid)
            {
                db.Profiles.Add(profile);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.AddressId = new SelectList(db.Addresses, "AddressId", "StreetAddress", profile.AddressId);
            ViewBag.UserId = new SelectList(db.Users, "Id", "Email", profile.UserId);
            ViewBag.RequestId = new SelectList(db.Requests, "RequestId", "Status", profile.RequestId);
            ViewBag.SubjectId = new SelectList(db.Subjects, "SubjectID", "SubjectName", profile.SubjectId);
            return View(profile);
        }

        // GET: List/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Profile profile = db.Profiles.Find(id);
            if (profile == null)
            {
                return HttpNotFound();
            }
            ViewBag.AddressId = new SelectList(db.Addresses, "AddressId", "StreetAddress", profile.AddressId);
            ViewBag.UserId = new SelectList(db.Users, "Id", "Email", profile.UserId);
            ViewBag.RequestId = new SelectList(db.Requests, "RequestId", "Status", profile.RequestId);
            ViewBag.SubjectId = new SelectList(db.Subjects, "SubjectID", "SubjectName", profile.SubjectId);
            return View(profile);
        }

        // POST: List/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ProfileId,UserId,AddressId,SubjectId,RequestId,ProfileFirstName,ProfileLastName,ProfilePhoneNumber,HourlyRate,MyDescription")] Profile profile)
        {
            if (ModelState.IsValid)
            {
                db.Entry(profile).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.AddressId = new SelectList(db.Addresses, "AddressId", "StreetAddress", profile.AddressId);
            ViewBag.UserId = new SelectList(db.Users, "Id", "Email", profile.UserId);
            ViewBag.RequestId = new SelectList(db.Requests, "RequestId", "Status", profile.RequestId);
            ViewBag.SubjectId = new SelectList(db.Subjects, "SubjectID", "SubjectName", profile.SubjectId);
            return View(profile);
        }

        // GET: List/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Profile profile = db.Profiles.Find(id);
            if (profile == null)
            {
                return HttpNotFound();
            }
            return View(profile);
        }

        // POST: List/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Profile profile = db.Profiles.Find(id);
            db.Profiles.Remove(profile);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

tutorHut/tutorHut/Views/List/Create.cshtml
@model tutorHut.Models.Profile

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Profile</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.UserId, "UserId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("UserId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.UserId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AddressId, "AddressId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("AddressId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.AddressId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SubjectId, "SubjectId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("SubjectId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SubjectId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RequestId, "RequestId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("RequestId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.RequestId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProfileFirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProfileFirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProfileFirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProfileLastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProfileLastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProfileLastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProfilePhoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProfilePhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProfilePhoneNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HourlyRate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HourlyRate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HourlyRate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MyDescription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MyDescription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MyDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

tutorHut/tutorHut/Views/List/Delete.cshtml
@model tutorHut.Models.Profile

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Profile</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Address.StreetAddress)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address.StreetAddress)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ApplicationUser.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ApplicationUser.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Request.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Request.Status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Subject.SubjectName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Subject.SubjectName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProfileFirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProfileFirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProfileLastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProfileLastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProfilePhoneNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProfilePhoneNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HourlyRate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HourlyRate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MyDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MyDescription)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

tutorHut/tutorHut/Views/List/Details.cshtml
@model tutorHut.Models.Profile

@{
    ViewBag.Title = "Details";
}

@*<h2>Details</h2>*@
<h2>Profile</h2>

<div>
    @*<h4>Profile</h4>*@
    <hr />
    <dl class="dl-horizontal">
        @*<dt>
            @Html.DisplayNameFor(model => model.Address.StreetAddress)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address.StreetAddress)
        </dd>*@

        <dt>
            @Html.DisplayNameFor(model => model.ApplicationUser.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ApplicationUser.Email)
        </dd>

        @*<dt>
            @Html.DisplayNameFor(model => model.Request.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Request.Status)
        </dd>*@

        <dt>
            @Html.DisplayNameFor(model => model.Subject.SubjectName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Subject.SubjectName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProfileFirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProfileFirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProfileLastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProfileLastName)
        </dd>

        @*<dt>
            @Html.DisplayNameFor(model => model.ProfilePhoneNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProfilePhoneNumber)
        </dd>*@

        <dt>
            @Html.DisplayNameFor(model => model.HourlyRate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HourlyRate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MyDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MyDescription)
        </dd>

    </dl>
</div>
<p>
    @*@Html.ActionLink("Edit", "Edit", new { id = Model.ProfileId }) |*@
    @Html.ActionLink("Back to List", "Index")
</p>

@using (Html.BeginForm("Details", "List", FormMethod.Post, new { @class = "Form-Horizontal", role = "form", enctype = "multipart/form-data" }))
{
    <div class="form-group">
        <div class="col-md-12">
            <input type="submit" value="Request Information" class="btn btn-default"  />
        </div>
    </div>
}

tutorHut/tutorHut/Views/List/Edit.cshtml
@model tutorHut.Models.Profile

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Profile</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ProfileId)

        <div class="form-group">
            @Html.LabelFor(model => model.UserId, "UserId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("UserId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.UserId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AddressId, "AddressId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("AddressId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.AddressId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SubjectId, "SubjectId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("SubjectId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SubjectId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RequestId, "RequestId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("RequestId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.RequestId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProfileFirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProfileFirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProfileFirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProfileLastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProfileLastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProfileLastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProfilePhoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ProfilePhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ProfilePhoneNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HourlyRate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HourlyRate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HourlyRate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MyDescription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MyDescription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MyDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

tutorHut/tutorHut/Views/List/Index.cshtml
@model IEnumerable<tutorHut.Models.Profile>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

@*<p>
    @Html.ActionLink("Create New", "Create")
</p>*@

<p>

    @*add this code*@

    
        @using (Html.BeginForm())
        {
        <p>
            Subject: @Html.TextBox("SearchString") <br />
            <input type="submit" value="Filter" />
        </p>
        }
    

</p>



<table class="table">
    <tr>
        @*<th>
            @Html.DisplayNameFor(model => model.Address.StreetAddress)
        </th>*@
        <th>
            @Html.DisplayNameFor(model => model.Address.ZipCode)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ApplicationUser.Email)
        </th>
        @*<th>
            @Html.DisplayNameFor(model => model.Request.Status)
        </th>*@
        <th>
            @Html.DisplayNameFor(model => model.Subject.SubjectName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ProfileFirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ProfileLastName)
        </th>
        @*<th>
            @Html.DisplayNameFor(model => model.ProfilePhoneNumber)
        </th>*@
        <th>
            @Html.DisplayNameFor(model => model.HourlyRate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MyDescription)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        @*<td>
            @Html.DisplayFor(modelItem => item.Address.StreetAddress)
        </td>*@
        <td>
            @Html.DisplayFor(modelItem => item.Address.ZipCode)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ApplicationUser.Email)
        </td>
        @*<td>
            @Html.DisplayFor(modelItem => item.Request.Status)
        </td>*@
        <td>
            @Html.DisplayFor(modelItem => item.Subject.SubjectName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ProfileFirstName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ProfileLastName)
        </td>
        @*<td>
            @Html.DisplayFor(modelItem => item.ProfilePhoneNumber)
        </td>*@
        <td>
            @Html.DisplayFor(modelItem => item.HourlyRate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.MyDescription)
        </td>
        <td>
            @*@Html.ActionLink("Edit", "Edit", new { id=item.ProfileId }) |*@
            @Html.ActionLink("Read More", "Details", new { id=item.ProfileId }) 
            @*@Html.ActionLink("Delete", "Delete", new { id=item.ProfileId })*@
        </td>
        @*<td>
            @Html.ActionLink("Details", "Details", new { id=item.ProfileId })
        </td>*@
    </tr>
}

</table>